// Auto-generated product & customer data for 218 Supply Order Pad
// Duplicated SKUs removed (keeping first occurrence).
// Rows with missing / zero MinSellPrice were skipped.

// Customers with IDs
window.customers = [
  { id: "CHALSTROMS", name: "Chalstroms", city: "Hermantown", state: "MN" },
  { id: "ROUND_UP", name: "Round Up", city: "Duluth", state: "MN" },
  { id: "RT_QUINLANS", name: "Rt Quinlans", city: "Duluth", state: "MN" },
  { id: "SNYDERS", name: "Snyders", city: "Duluth", state: "MN" },
  { id: "HERMANTOWN_KORNER_STORE", name: "Hermantown Korner Store", city: "Hermantown", state: "MN" },
  { id: "BERGEYS", name: "Bergeys", city: "Duluth", state: "MN" },
  { id: "RUSTIC_BAR", name: "Rustic Bar", city: "Duluth", state: "MN" },
  { id: "MR._D'S", name: "Mr. D's", city: "Duluth", state: "MN" },
  { id: "KOM_ON_INN", name: "Kom On Inn", city: "Duluth", state: "MN" },
  { id: "TAPPA_KEG", name: "Tappa Keg", city: "Duluth", state: "MN" },
  { id: "DULUTH_KORNER_STORE_000", name: "Duluth Korner Store 000", city: "Duluth", state: "MN" },
  { id: "DULUTH_KORNER_STORE_700", name: "Duluth Korner Store 700", city: "Duluth", state: "MN" },
  { id: "ALPINE_BAR", name: "Alpine Bar", city: "Duluth", state: "MN" },
  { id: "EL_DORADO", name: "El Dorado", city: "Oliver", state: "WI" },
  { id: "BIRD'S_BAR", name: "Bird'S Bar", city: "Superior", state: "WI" },
  { id: "THE_SHACK", name: "The Shack", city: "Superior", state: "WI" },
  { id: "STRIKERS", name: "Strikers", city: "Superior", state: "WI" },
  { id: "SUPERIOR_EAGLES", name: "Superior Eagles", city: "Superior", state: "WI" },
  { id: "TOWER_AVE_TAVERN", name: "Tower Ave Tavern", city: "Superior", state: "WI" },
  { id: "IZZYS", name: "Izzys", city: "Superior", state: "WI" },
  { id: "SUPERIOR_KORNER_STORE", name: "Superior Korner Store", city: "Superior", state: "WI" },
  { id: "NORTHLAND_PHARMACY", name: "Northland Pharmacy", city: "Duluth", state: "MN" },
  { id: "LAKE_WALK_PHARMACY", name: "Lake Walk Pharmacy", city: "Duluth", state: "MN" },
  { id: "ROSCOES", name: "Roscoes", city: "Duluth", state: "MN" },
  { id: "TWO_HARBORS_MOOSE", name: "Two Harbors Moose", city: "Two Harbors", state: "MN" },
  { id: "TWO_HARBORS_LEGION", name: "Two Harbors Legion", city: "Two Harbors", state: "MN" },
  { id: "THE_LANDING", name: "The Landing", city: "Two Harbors", state: "MN" },
  { id: "HI_BANKS", name: "Hi Banks", city: "Duluth", state: "MN" },
  { id: "BLUE_MAX", name: "Blue Max", city: "Duluth", state: "MN" },
  { id: "FOUR_SEASONS_MEAT", name: "Four Seasons Meat", city: "Coleraine", state: "MN" },
  { id: "B&B_MARKET", name: "B&B Market", city: "Cloquet", state: "MN" },
  { id: "BARNUM_LIQUOR", name: "Barnum Liquor", city: "Barnum", state: "MN" },
  { id: "BLUEBERRY_BOWL", name: "Blueberry Bowl", city: "Deer River", state: "MN" },
  { id: "BRICKS", name: "Bricks", city: "Mahtowa", state: "MN" },
  { id: "CARLTON_MEAT", name: "Carlton Meat", city: "Carlton", state: "MN" },
  { id: "CARLTON_BFW", name: "Carlton Bfw", city: "Carlton", state: "MN" },
  { id: "CAYWOOD_COUNTRY_STORE", name: "Caywood Country Store", city: "Saginaw", state: "MN" },
  { id: "COOK_MUNI_BAR", name: "Cook Muni Bar", city: "Cook", state: "MN" },
  { id: "COUNTRY_CORNER", name: "Country Corner", city: "Brookston Legion", state: "MN" },
  { id: "CROMWELL_LIQUOR", name: "Cromwell Liquor", city: "Cromwell", state: "MN" },
  { id: "GRAND_RAPIDS_EAGLES", name: "Grand Rapids Eagles", city: "Grand Rapids", state: "MN" },
  { id: "HOTEL_RAPIDS", name: "Hotel Rapids", city: "Grand Rapids", state: "MN" },
  { id: "IM_HOTEL", name: "IM Hotel", city: "Grand Rapids", state: "MN" },
  { id: "CHISHOLM_VAUGHN", name: "Chisholm Vaughn", city: "Chisholm", state: "MN" },
  { id: "KNUCKLEHEADS", name: "Knuckleheads", city: "Hill City", state: "MN" },
  { id: "CORNER_STORE", name: "Korner Store", city: "Chisholm", state: "MN" },
  { id: "LARRY'S_SERVICE", name: "Larry'S Service", city: "Floodwood", state: "MN" },
  { id: "LAST_CHANCE_LIQUOR", name: "Last Chance Liquor", city: "Cook", state: "MN" },
  { id: "LOCKER_ROOM", name: "Locker Room", city: "Coleraine", state: "MN" },
  { id: "MOTTAWA_TAVERN", name: "Mottawa Tavern", city: "Mahtowa", state: "MN" },
  { id: "NORMANS", name: "Normans", city: "Orr", state: "MN" },
  { id: "NORTHWOODS_MEAT", name: "Northwoods Meat", city: "Remer", state: "MN" },
  { id: "ORR_MUNI", name: "Orr Muni", city: "Orr", state: "MN" },
  { id: "PELICAN_BAY_FOODS", name: "Pelican Bay Foods", city: "Orr", state: "MN" },
  { id: "POWERHOUSE", name: "Powerhouse", city: "Proctor", state: "MN" },
  { id: "PROCTOR_KEYBOARD", name: "Proctor Keyboard", city: "Proctor", state: "MN" },
  { id: "PROCTOR_MOOSE", name: "Proctor Moose", city: "Proctor", state: "MN" },
  { id: "REAMER_BAR", name: "Reamer Bar", city: "Remer", state: "MN" },
  { id: "REAMER_LIQUOR_STORE", name: "Reamer Liquor Store", city: "Remer", state: "MN" },
  { id: "RIVER_INN", name: "River Inn", city: "Cloquet", state: "MN" },
  { id: "S&S_MEATS", name: "S&S Meats", city: "Grand Rapids", state: "MN" },
  { id: "T_PATTON'S", name: "T Patton'S", city: "Orr", state: "MN" },
  { id: "THE_JACK", name: "The Jack", city: "Cloquet", state: "MN" },
  { id: "3RD_BASE", name: "3rd Base", city: "Carlton", state: "MN" },
  { id: "TJ'S", name: "TJ's", city: "Mahtowa", state: "MN" },
  { id: "TOM_&_JERRY'S", name: "Tom & Jerry's", city: "Chisholm", state: "MN" },
  { id: "VALENTINI'S", name: "Valentini'S", city: "Chisholm", state: "MN" },
  { id: "WIZARDS", name: "Wizards", city: "Nahauwauk", state: "MN" },
];

window.products = [
  { sku: "E178001", category: "Cutlery", name: "MED WRAPPED FORK", pack: "1M/CS", packSize: "1M/CS", price: 37.96, active: true },
  { sku: "E178002", category: "Cutlery", name: "MED WRAPPED SPOON", pack: "1M/CS", packSize: "1M/CS", price: 37.96, active: true },
  { sku: "E178003", category: "Cutlery", name: "MED WRAPPED KNIFE", pack: "1M/CS", packSize: "1M/CS", price: 37.96, active: true },
  { sku: "E178004", category: "Cutlery", name: "MED WRAPPED SOUP SPOON", pack: "1M/CS", packSize: "1M/CS", price: 37.96, active: true },
  { sku: "E175001", category: "Cutlery", name: "BULK MED FORK", pack: "1M/CS", packSize: "1M/CS", price: 16.39, active: true },
  { sku: "E175002", category: "Cutlery", name: "BULK MED SPOON", pack: "1M/CS", packSize: "1M/CS", price: 16.39, active: true },
  { sku: "E175003", category: "Cutlery", name: "BULK MED KNIFE", pack: "1M/CS", packSize: "1M/CS", price: 16.39, active: true },
  { sku: "E175040", category: "Cutlery", name: "BULK MED SOUP SPOON", pack: "1M/CS", packSize: "1M/CS", price: 16.39, active: true },
  { sku: "E175020", category: "Cutlery", name: "BULK MED SPORK", pack: "1M/CS", packSize: "1M/CS", price: 16.39, active: true },
  { sku: "E179001", category: "Cutlery", name: "HW BLACK FORK", pack: "1M/CS", packSize: "1M/CS", price: 25.66, active: true },
  { sku: "E179002", category: "Cutlery", name: "HW BLACK SPOON", pack: "1M/CS", packSize: "1M/CS", price: 25.66, active: true },
  { sku: "E179003", category: "Cutlery", name: "HW BLACK KNIFE", pack: "1M/CS", packSize: "1M/CS", price: 25.66, active: true },
  { sku: "E172001", category: "Cutlery", name: "XHW BLACK FORK", pack: "1M/CS", packSize: "1M/CS", price: 93.14, active: true },
  { sku: "E172002", category: "Cutlery", name: "XHW BLACK SPOON SP OR", pack: "1M/CS", packSize: "1M/CS", price: 93.14, active: true },
  { sku: "E172003", category: "Cutlery", name: "XHW BLACK KNIFE", pack: "1M/CS", packSize: "1M/CS", price: 93.14, active: true },
  { sku: "E181001", category: "Cutlery", name: "HW WHITE FORK", pack: "1M/CS", packSize: "1M/CS", price: 29.60, active: true },
  { sku: "E181002", category: "Cutlery", name: "HW WHITE SPOON", pack: "1M/CS", packSize: "1M/CS", price: 29.60, active: true },
  { sku: "E181003", category: "Cutlery", name: "HW WHITE KNIFE", pack: "1M/CS", packSize: "1M/CS", price: 29.60, active: true },
  { sku: "E182001", category: "Cutlery", name: "HW CHAMPAGNE FORK", pack: "1M/CS", packSize: "1M/CS", price: 35.37, active: true },
  { sku: "E182002", category: "Cutlery", name: "HW CHAMPAGNE SPOON", pack: "1M/CS", packSize: "1M/CS", price: 35.37, active: true },
  { sku: "E182003", category: "Cutlery", name: "HW CHAMPAGNE KNIFE SO", pack: "1M/CS", packSize: "1M/CS", price: 35.37, active: true },
  { sku: "E171001", category: "Cutlery", name: "XHW WHITE FORK", pack: "1M/CS", packSize: "1M/CS", price: 93.14, active: true },
  { sku: "E171002", category: "Cutlery", name: "XHW WHITE SPOON", pack: "1M/CS", packSize: "1M/CS", price: 93.14, active: true },
  { sku: "E171003", category: "Cutlery", name: "XHW WHITE KNIFE", pack: "1M/CS", packSize: "1M/CS", price: 93.14, active: true },
  { sku: "E189004", category: "Cutlery", name: "HW WRAPPED SOUP SPOON", pack: "1M/CS", packSize: "1M/CS", price: 36.73, active: true },
  { sku: "NOVA3000", category: "Napkins", name: "DINNER NAP", pack: "20-135/CS", packSize: "20-135/CS", price: 49.04, active: true },
  { sku: "NOVAQS10647", category: "Napkins", name: "DISPENSER NAP", pack: "24-250/CS", packSize: "24-250/CS", price: 39.74, active: true },
  { sku: "RPNB85001V", category: "Napkins", name: "BEVERAGE NAP", pack: "8-500/CS", packSize: "8-500/CS", price: 19.79, active: true },
  { sku: "BWK500NAP", category: "Napkins", name: "LUNCHEON NAP", pack: "6-500/CS", packSize: "6-500/CS", price: 52.87, active: true },
  { sku: "BWK8307W", category: "Napkins", name: "DINNER NAP", pack: "12-250/CS", packSize: "12-250/CS", price: 68.04, active: true },
  { sku: "BWK8316W", category: "Napkins", name: "LOFOLD NAP", pack: "20-400/CS", packSize: "20-400/CS", price: 48.16, active: true },
  { sku: "NOVA-FACIAL", category: "Napkins", name: "FLAT BOX", pack: "30-100/CS", packSize: "30-100/CS", price: 25.33, active: true },
  { sku: "8904", category: "Napkins", name: "CUBE BOX", pack: "36-90/CS", packSize: "36-90/CS", price: 72.96, active: true },
  { sku: "ITEM-0034", category: "Meat Snacks", name: "Original Jerky", pack: "10ct", packSize: "10ct", price: 17.85, active: true },
  { sku: "ITEM-0035", category: "Meat Snacks", name: "Teriyaki Jerky", pack: "10ct", packSize: "10ct", price: 17.85, active: true },
  { sku: "ITEM-0036", category: "Meat Snacks", name: "Jalapeno Jerky", pack: "10ct", packSize: "10ct", price: 17.85, active: true },
  { sku: "ITEM-0037", category: "Meat Snacks", name: "Peppered Jerky", pack: "10ct", packSize: "10ct", price: 17.85, active: true },
  { sku: "ITEM-0038", category: "Meat Snacks", name: "Old Fashion Jerky", pack: "10ct", packSize: "10ct", price: 17.85, active: true },
  { sku: "ITEM-0039", category: "Meat Snacks", name: "Empty Jars w/Lids", pack: "3ct", packSize: "3ct", price: 6.29, active: true },
  { sku: "ITEM-0040", category: "Meat Snacks", name: "Original Jerky 3oz", pack: "3oz", packSize: "3oz", price: 7.51, active: true },
  { sku: "ITEM-0041", category: "Meat Snacks", name: "Teriyaki Jerky 3oz", pack: "3oz", packSize: "3oz", price: 7.51, active: true },
  { sku: "ITEM-0042", category: "Meat Snacks", name: "Jalapeno Jerky 3oz", pack: "3oz", packSize: "3oz", price: 7.51, active: true },
  { sku: "ITEM-0043", category: "Meat Snacks", name: "Peppered Jerky 3oz", pack: "3oz", packSize: "3oz", price: 7.51, active: true },
  { sku: "ITEM-0044", category: "Meat Snacks", name: "Old Fashion Jerky 3oz", pack: "3oz", packSize: "3oz", price: 7.51, active: true },
  { sku: "ITEM-0045", category: "Meat Snacks", name: "Kickass Mini Sausage", pack: "16ct", packSize: "16ct", price: 22.91, active: true },
  { sku: "ITEM-0046", category: "Meat Snacks", name: "Original 2pk Sticks", pack: "16ct", packSize: "16ct", price: 31.99, active: true },
  { sku: "ITEM-0047", category: "Meat Snacks", name: "Teriyaki 2pk Sticks", pack: "16ct", packSize: "16ct", price: 31.99, active: true },
  { sku: "ITEM-0048", category: "Meat Snacks", name: "Summer Sausage 2pk Sticks", pack: "16ct", packSize: "16ct", price: 31.99, active: true },
  { sku: "ITEM-0049", category: "Meat Snacks", name: "HoneyBBQ 2pk Sticks", pack: "16ct", packSize: "16ct", price: 31.99, active: true },
  { sku: "ITEM-0050", category: "Meat Snacks", name: "Spicy 2pk Sticks", pack: "16ct", packSize: "16ct", price: 31.99, active: true },
  { sku: "ITEM-0051", category: "Meat Snacks", name: "Jalapeno/Cheddar 2pk Sticks", pack: "16ct", packSize: "16ct", price: 31.99, active: true },
  { sku: "ITEM-0052", category: "Meat Snacks", name: "Bac/Ched 2pk Snack", pack: "16ct", packSize: "16ct", price: 31.99, active: true },
  { sku: "ITEM-0053", category: "Meat Snacks", name: "Garlic 2pk Snack", pack: "16ct", packSize: "16ct", price: 31.99, active: true },
  { sku: "ITEM-0054", category: "Meat Snacks", name: "Sausage/Cheddar 2pk Sticks", pack: "21ct", packSize: "21ct", price: 40.39, active: true },
  { sku: "ITEM-0055", category: "Bar", name: "Bloody Mary Mix 32oz", pack: "12ct", packSize: "12ct", price: 65.83, active: true },
  { sku: "ITEM-0056", category: "Bar", name: "Bloody Mary Mix 32oz", pack: "Each", packSize: "Each", price: 6.46, active: true },
  { sku: "ITEM-0057", category: "Meat Snacks", name: "Cooler Pack Original 7/1oz", pack: "12ct", packSize: "12ct", price: 77.56, active: true },
  { sku: "ITEM-0058", category: "Meat Snacks", name: "Cooler Pack Spicy 7/1oz", pack: "12ct", packSize: "12ct", price: 77.56, active: true },
  { sku: "ITEM-0059", category: "Meat Snacks", name: "Cooler Pack Bac/Ched 7/1oz", pack: "12ct", packSize: "12ct", price: 77.56, active: true },
  { sku: "ITEM-0060", category: "Meat Snacks", name: "Cooler Pack Jal/Ched 7/1oz", pack: "12ct", packSize: "12ct", price: 77.56, active: true },
  { sku: "ITEM-0061", category: "Meat Snacks", name: "Kippered Original 1oz", pack: "12ct", packSize: "12ct", price: 25.53, active: true },
  { sku: "ITEM-0062", category: "Meat Snacks", name: "Kippered Teriyaki 1oz", pack: "12ct", packSize: "12ct", price: 25.53, active: true },
  { sku: "ITEM-0063", category: "Meat Snacks", name: "Kippered Swt/Hot 1oz", pack: "12ct", packSize: "12ct", price: 25.53, active: true },
  { sku: "ITEM-0064", category: "Meat Snacks", name: "Original/Mild Snack Stick", pack: "20ct", packSize: "20ct", price: 18.00, active: true },
  { sku: "ITEM-0065", category: "Meat Snacks", name: "Hot", pack: "20ct", packSize: "20ct", price: 18.00, active: true },
  { sku: "ITEM-0066", category: "Meat Snacks", name: "Bloody Mary", pack: "20ct", packSize: "20ct", price: 18.00, active: true },
  { sku: "ITEM-0067", category: "Meat Snacks", name: "Mandarin Teriyaki", pack: "20ct", packSize: "20ct", price: 18.00, active: true },
  { sku: "ITEM-0068", category: "Meat Snacks", name: "Pepperoni", pack: "20ct", packSize: "20ct", price: 18.00, active: true },
  { sku: "ITEM-0069", category: "Meat Snacks", name: "Pepper Cheese", pack: "20ct", packSize: "20ct", price: 18.00, active: true },
  { sku: "ITEM-0070", category: "Meat Snacks", name: "Honey BBQ", pack: "20ct", packSize: "20ct", price: 18.00, active: true },
  { sku: "ITEM-0071", category: "Meat Snacks", name: "Buffalo", pack: "20ct", packSize: "20ct", price: 18.00, active: true },
  { sku: "ITEM-0072", category: "Meat Snacks", name: "Dill Pickle", pack: "20ct", packSize: "20ct", price: 18.00, active: true },
  { sku: "ITEM-0073", category: "Meat Snacks", name: "Memphis BBQ", pack: "20ct", packSize: "20ct", price: 18.00, active: true },
  { sku: "ITEM-0074", category: "Meat Snacks", name: "Philly Steak", pack: "20ct", packSize: "20ct", price: 18.00, active: true },
  { sku: "V-0608", category: "Vac Pac Bags", name: "6X8 3MIL VACPAK BAG", pack: "1M/CS", packSize: "1M/CS", price: 36.30, active: true },
  { sku: "V-0610", category: "Vac Pac Bags", name: "6X10 3MIL VACPAK BAG", pack: "1M/CS", packSize: "1M/CS", price: 44.99, active: true },
  { sku: "V-0612", category: "Vac Pac Bags", name: "6X12 3MIL VACPAK BAG", pack: "1M/CS", packSize: "1M/CS", price: 53.70, active: true },
  { sku: "V-0615", category: "Vac Pac Bags", name: "6X15 3MIL VACPAK BAG", pack: "1M/CS", packSize: "1M/CS", price: 66.76, active: true },
  { sku: "V-0711", category: "Vac Pac Bags", name: "7X11 3MIL VACPAK BAG", pack: "1M/CS", packSize: "1M/CS", price: 57.33, active: true },
  { sku: "V-0810", category: "Vac Pac Bags", name: "8X10 3MIL VACPAK BAG", pack: "1M/CS", packSize: "1M/CS", price: 59.50, active: true },
  { sku: "V-0812", category: "Vac Pac Bags", name: "8X12 3MIL VACPAK BAG", pack: "1M/CS", packSize: "1M/CS", price: 71.11, active: true },
  { sku: "V-0815", category: "Vac Pac Bags", name: "8X15 3MIL VACPAK BAG", pack: "1M/CS", packSize: "1M/CS", price: 88.53, active: true },
  { sku: "V-0818", category: "Vac Pac Bags", name: "8X18 4MIL VACPAK BAG", pack: "1M/CS", packSize: "1M/CS", price: 143.41, active: true },
  { sku: "V-1013", category: "Vac Pac Bags", name: "10X13 3MIL VACPAK BAG", pack: "1M/CS", packSize: "1M/CS", price: 95.76, active: true },
  { sku: "V-1015", category: "Vac Pac Bags", name: "10X15 3MIL VACPAK BAG", pack: "1M/CS", packSize: "1M/CS", price: 110.29, active: true },
  { sku: "V-1215", category: "Vac Pac Bags", name: "12X15 3MIL VACPAK BAG", pack: "1M/CS", packSize: "1M/CS", price: 132.04, active: true },
  { sku: "V-1216", category: "Vac Pac Bags", name: "12X16 4MIL VACPAK BAG", pack: "1M/CS", packSize: "1M/CS", price: 190.74, active: true },
  { sku: "V-1420", category: "Vac Pac Bags", name: "14X20 3MIL VACPAK BAG", pack: "500/CS", packSize: "500/CS", price: 100.03, active: true },
  { sku: "V-1620", category: "Vac Pac Bags", name: "16X20 3MIL VACPAK BAG", pack: "250/CS", packSize: "250/CS", price: 59.50, active: true },
  { sku: "V-8612", category: "Vac Pac Bags", name: "8.6X12.3 4MIL VACPAK BAG", pack: "1M/CS", packSize: "1M/CS", price: 105.73, active: true },
  { sku: "B72210XX", category: "Can Liners", name: "20X21 7-10GL", pack: "20/50/CS", packSize: "20/50/CS", price: 29.89, active: true },
  { sku: "SL2432100K", category: "Can Liners", name: "24X32 12-16GL 1MIL", pack: "10/50/CS", packSize: "10/50/CS", price: 49.51, active: true },
  { sku: "PL3036XHBB", category: "Can Liners", name: "30X36 20-30GL .8MIL", pack: "10/25/CS", packSize: "10/25/CS", price: 33.21, active: true },
  { sku: "SM333915", category: "Can Liners", name: "33X39 33GL 28MIC", pack: "10/10/CS", packSize: "10/10/CS", price: 21.56, active: true },
  { sku: "SM404615", category: "Can Liners", name: "40X46 40-45GL 28MIC", pack: "10/10/CS", packSize: "10/10/CS", price: 30.76, active: true },
  { sku: "SM434715", category: "Can Liners", name: "43X47 56GL 28MIC", pack: "10/10/CS", packSize: "10/10/CS", price: 34.51, active: true },
  { sku: "SM385820", category: "Can Liners", name: "38X58 60GL 28MIC", pack: "10/10/CS", packSize: "10/10/CS", price: 36.49, active: true },
  { sku: "SM385828", category: "Can Liners", name: "38X58 60GL 51MIC", pack: "5/10/CS", packSize: "5/10/CS", price: 32.74, active: true },
  { sku: "EC202206N", category: "Can Liners", name: "20X22 7-10GL 6MIC", pack: "40/50/CS", packSize: "40/50/CS", price: 37.83, active: true },
  { sku: "PH242408N", category: "Can Liners", name: "24X24 7-10GL .24MIL", pack: "20/50/CS", packSize: "20/50/CS", price: 27.43, active: true },
  { sku: "PH243308N", category: "Can Liners", name: "24X33 12-16GL .24MIL", pack: "20/50/CS", packSize: "20/50/CS", price: 36.61, active: true },
  { sku: "SMH303610", category: "Can Liners", name: "30X36 20-30GL .24MIL", pack: "20/25/CS", packSize: "20/25/CS", price: 40.31, active: true },
  { sku: "PH334016N", category: "Can Liners", name: "33X40 33GL .55MIL", pack: "10/25/CS", packSize: "10/25/CS", price: 30.53, active: true },
  { sku: "PH404816N", category: "Can Liners", name: "40X46 40-45GL .55MIL", pack: "10/25/CS", packSize: "10/25/CS", price: 41.80, active: true },
  { sku: "PH386017N", category: "Can Liners", name: "38X58 60GL .55MIL", pack: "8/25/CS", packSize: "8/25/CS", price: 40.86, active: true },
  { sku: "MT403XW", category: "Can Liners", name: "33X39 33GL .95MIL", pack: "10/15/CS", packSize: "10/15/CS", price: 32.73, active: true },
  { sku: "MT603XW", category: "Can Liners", name: "38X58 60GL .95MIL", pack: "10/10/CS", packSize: "10/10/CS", price: 37.04, active: true },
  { sku: "60HT1", category: "Dart Foam", name: "6X6 HINGE TOGO", pack: "4-125/CS", packSize: "4-125/CS", price: 35.93, active: true },
  { sku: "205HT1", category: "Dart Foam", name: "6X9X3 HINGE TOGO", pack: "2-100/CS", packSize: "2-100/CS", price: 27.43, active: true },
  { sku: "95HT1", category: "Dart Foam", name: "9X9X3 HINGE TOGO", pack: "2-100/CS", packSize: "2-100/CS", price: 36.29, active: true },
  { sku: "8SJ20", category: "Dart Foam", name: "8OZ SQUAT CUP", pack: "20-50/CS", packSize: "20-50/CS", price: 81.24, active: true },
  { sku: "12SJ20", category: "Dart Foam", name: "12OZ SQUAT CUP", pack: "20-50/CS", packSize: "20-50/CS", price: 85.53, active: true },
  { sku: "16MJ20", category: "Dart Foam", name: "16OZ SQUAT CUP", pack: "20-25/CS", packSize: "20-25/CS", price: 54.74, active: true },
  { sku: "8B20", category: "Dart Foam", name: "8OZ BOWL", pack: "20-50/CS", packSize: "20-50/CS", price: 79.81, active: true },
  { sku: "12BWWCR", category: "Dart Foam", name: "12OZ RIM BOWL", pack: "8-125/CS", packSize: "8-125/CS", price: 39.67, active: true },
  { sku: "4J6", category: "Dart Foam", name: "4OZ SQUAT CUP", pack: "20-50/CS", packSize: "20-50/CS", price: 30.31, active: true },
  { sku: "6PWCR", category: "Dart Foam", name: "6\" FOAM PLATE", pack: "4-125/CS", packSize: "4-125/CS", price: 29.89, active: true },
  { sku: "9PWCR", category: "Dart Foam", name: "9\" FOAM PLATE", pack: "4-125/CS", packSize: "4-125/CS", price: 30.50, active: true },
  { sku: "10PWCR", category: "Dart Foam", name: "10\" FOAM PLATE", pack: "4-125/CS", packSize: "4-125/CS", price: 39.77, active: true },
  { sku: "YTH80500", category: "Dart Foam", name: "SCHOOL TRAY", pack: "500/CS", packSize: "500/CS", price: 48.70, active: true },
  { sku: "6JL", category: "Dart Foam", name: "4J6 LID", pack: "10-100/CS", packSize: "10-100/CS", price: 31.39, active: true },
  { sku: "20RL", category: "Dart Foam", name: "FOAM 20 SERIES LID", pack: "10-100/CS", packSize: "10-100/CS", price: 47.36, active: true },
  { sku: "20JL", category: "Dart Foam", name: "CLEAR VENT 20 SERIES LID", pack: "10-100/CS", packSize: "10-100/CS", price: 50.89, active: true },
  { sku: "B040", category: "Toilet Tissue", name: "2PLY", pack: "96/500/CS", packSize: "96/500/CS", price: 58.03, active: true },
  { sku: "4100020", category: "Toilet Tissue", name: "1PLY", pack: "96/1000/CS", packSize: "96/1000/CS", price: 93.33, active: true },
  { sku: "NOVA1000", category: "Toilet Tissue", name: "2PLY JUMBO", pack: "12/1000/CS", packSize: "12/1000/CS", price: 34.04, active: true },
  { sku: "T150", category: "Toilet Tissue", name: "CASCADES", pack: "36/950/CS", packSize: "36/950/CS", price: 88.67, active: true },
  { sku: "NOVA800N", category: "Toilet Tissue", name: "BROWN ROLL TOWEL", pack: "6/800/CS", packSize: "6/800/CS", price: 31.39, active: true },
  { sku: "NOVA800W", category: "Toilet Tissue", name: "WHITE ROLL TOWEL", pack: "6/800/CS", packSize: "6/800/CS", price: 31.39, active: true },
  { sku: "NOVA3085", category: "Toilet Tissue", name: "KITCHEN TOWEL", pack: "30/85/CS", packSize: "30/85/CS", price: 32.33, active: true },
  { sku: "1080061", category: "Toilet Tissue", name: "10\" ENMOTION", pack: "6RL/CS", packSize: "6RL/CS", price: 64.63, active: true },
  { sku: "CP660010", category: "Toilet Tissue", name: "CENTERPULL", pack: "6/600/CS", packSize: "6/600/CS", price: 35.70, active: true },
  { sku: "NOVA275SK", category: "Toilet Tissue", name: "BROWN SINGLEFOLD", pack: "16/250/CS", packSize: "16/250/CS", price: 34.91, active: true },
  { sku: "NOVAMK250", category: "Toilet Tissue", name: "BROWN MULTIFOLD", pack: "16/250/CS", packSize: "16/250/CS", price: 39.43, active: true },
  { sku: "HT40011", category: "Toilet Tissue", name: "WHITE MULTIFOLD", pack: "12/334/CS", packSize: "12/334/CS", price: 29.79, active: true },
  { sku: "T115", category: "Toilet Tissue", name: "BROWN CASCADES", pack: "6RL/CS", packSize: "6RL/CS", price: 70.79, active: true },
  { sku: "T116", category: "Toilet Tissue", name: "WHITE CASCADES", pack: "6RL/CS", packSize: "6RL/CS", price: 91.64, active: true },
  { sku: "89440", category: "Toilet Tissue", name: "TORK ENMOTION", pack: "6RL/CS", packSize: "6RL/CS", price: 109.81, active: true },
  { sku: "290088", category: "Toilet Tissue", name: "BROWN TORK", pack: "6RL/CS", packSize: "6RL/CS", price: 86.16, active: true },
  { sku: "5123", category: "Toilet Tissue", name: "BLUE WINDSHIELD", pack: "10/224/CS", packSize: "10/224/CS", price: 69.05, active: true },
  { sku: "W430", category: "Toilet Tissue", name: "WIPER", pack: "8/100/CS", packSize: "8/100/CS", price: 79.03, active: true },
  { sku: "W900", category: "Toilet Tissue", name: "FOODSERVICE WIPER", pack: "200/CS", packSize: "200/CS", price: 34.25, active: true },
  { sku: "PK25", category: "Toilet Tissue", name: "RECLAIMED RAGS", pack: "25#/BX", packSize: "25#/BX", price: 60.41, active: true },
  { sku: "EVPFS4001", category: "Gloves", name: "SMALL PF VINYL", pack: "10-100/CS", packSize: "10-100/CS", price: 43.04, active: true },
  { sku: "EVPFM4002", category: "Gloves", name: "MED PF VINYL", pack: "10-100/CS", packSize: "10-100/CS", price: 29.77, active: true },
  { sku: "EVPFL4003", category: "Gloves", name: "LG PF VINYL", pack: "10-100/CS", packSize: "10-100/CS", price: 29.77, active: true },
  { sku: "EVPFXL4004", category: "Gloves", name: "XL PF VINYL", pack: "10-100/CS", packSize: "10-100/CS", price: 29.77, active: true },
  { sku: "EVPFXL4005", category: "Gloves", name: "XXL PF VINYL", pack: "10-100/CS", packSize: "10-100/CS", price: 57.07, active: true },
  { sku: "EVPL3004", category: "Gloves", name: "L P VINYL", pack: "10-100/CS", packSize: "10-100/CS", price: 38.21, active: true },
  { sku: "IM0403", category: "Gloves", name: "MED PF LATEX", pack: "10-100/CS", packSize: "10-100/CS", price: 59.44, active: true },
  { sku: "IM0404", category: "Gloves", name: "LG PF LATEX", pack: "10-100/CS", packSize: "10-100/CS", price: 59.44, active: true },
  { sku: "IM0405", category: "Gloves", name: "XL PF LATEX", pack: "10-100/CS", packSize: "10-100/CS", price: 59.44, active: true },
  { sku: "ENPFM2002", category: "Gloves", name: "MED NITRILE", pack: "10-100/CS", packSize: "10-100/CS", price: 57.30, active: true },
  { sku: "ENPFL2003", category: "Gloves", name: "LG NITRILE", pack: "10-100/CS", packSize: "10-100/CS", price: 54.61, active: true },
  { sku: "ENPFXL2004", category: "Gloves", name: "XL NITRILE", pack: "10-100/CS", packSize: "10-100/CS", price: 55.33, active: true },
  { sku: "GL-MEDIUM", category: "Gloves", name: "MED POLY", pack: "10-100/CS", packSize: "10-100/CS", price: 8.64, active: true },
  { sku: "GL-LARGE/P6003", category: "Gloves", name: "LG POLY", pack: "10-100/CS", packSize: "10-100/CS", price: 15.03, active: true },
  { sku: "116", category: "BAG", name: "1/6 THANK YOU BAG", pack: "1000/CS", packSize: "1000/CS", price: 36.64, active: true },
  { sku: "18404", category: "BAG", name: "4# BROWN BAG - 5X3.13X9.75", pack: "500/BL", packSize: "500/BL", price: 14.89, active: true },
  { sku: "18406", category: "BAG", name: "6# BROWN BAG - 6X3.63X11.06", pack: "500/BL", packSize: "500/BL", price: 20.03, active: true },
  { sku: "18408", category: "BAG", name: "8# BROWN BAG - 6.13X4.13X12.44", pack: "500/BL", packSize: "500/BL", price: 22.97, active: true },
  { sku: "18410", category: "BAG", name: "10# BROWN BAG - 6.31X4.19X13.38", pack: "500/BL", packSize: "500/BL", price: 26.30, active: true },
  { sku: "18412", category: "BAG", name: "12# BROWN BAG - 7.06X4.5X13.75", pack: "500/BL", packSize: "500/BL", price: 29.37, active: true },
  { sku: "18428", category: "BAG", name: "25# SQUAT 8.25X6.13X15.88", pack: "500/BL", packSize: "500/BL", price: 42.27, active: true },
  { sku: "70212", category: "BAG", name: "12# HEAVY DUTY BROWN BAG 7.06X4.5X13.75", pack: "400/BL", packSize: "400/BL", price: 30.70, active: true },
  { sku: "70221", category: "BAG", name: "20# HEAVY DUTY BROWN BAG 8.25X5.31X13.38", pack: "500/BL", packSize: "500/BL", price: 37.87, active: true },
  { sku: "71021", category: "BAG", name: "20# SQUAT BULWARK", pack: "500/BL", packSize: "500/BL", price: 43.96, active: true },
  { sku: "80076", category: "BAG", name: "1/6 BBL 57# 12X7X17", pack: "500/BL", packSize: "500/BL", price: 72.29, active: true },
  { sku: "80080", category: "BAG", name: "1/6 BBL 76# 12X7X17", pack: "500/BL", packSize: "500/BL", price: 81.84, active: true },
  { sku: "80083", category: "BAG", name: "1/8 BBL 57# 10.13X6.75X14.38", pack: "500/BL", packSize: "500/BL", price: 62.09, active: true },
  { sku: "T38017", category: "BAG", name: "HIPPO SACK", pack: "1000/CS", packSize: "1000/CS", price: 79.11, active: true },
  { sku: "CHERRY", category: "BAR", name: "CHERRIES - 1/2 GALLON", pack: "6 / CS", packSize: "6 / CS", price: 21.77, active: true },
  { sku: "GRENADINE", category: "BAR", name: "GRENADINE - ROSES - 25 OZ", pack: "EA", packSize: "EA", price: 7.75, active: true },
  { sku: "LIMEJUICE", category: "BAR", name: "LIME JUICE - ROSES - 25 OZ", pack: "EA", packSize: "EA", price: 7.75, active: true },
  { sku: "OLIVE", category: "BAR", name: "OLIVES - 1 GALLON", pack: "4 / CS", packSize: "4 / CS", price: 34.09, active: true },
  { sku: "PICKLE", category: "BAR", name: "PICKLE SPEARS - 1 GALLON", pack: "4 / CS", packSize: "4 / CS", price: 21.58, active: true },
  { sku: "SQZLEM", category: "BAR", name: "SQUEEZE LEMON - 4.5 OZ", pack: "EA", packSize: "EA", price: 0.87, active: true },
  { sku: "SQZLIME", category: "BAR", name: "SQUEEZE LIME - 4.5 OZ", pack: "EA", packSize: "EA", price: 0.87, active: true },
  { sku: "10B20", category: "BOWL", name: "10 OZ FOAM BOWL", pack: "50-20 / CS", packSize: "50-20 / CS", price: 92.19, active: true },
  { sku: "12B32", category: "BOWL", name: "12 OZ FOAM BOWL", pack: "50-20 / CS", packSize: "50-20 / CS", price: 105.99, active: true },
  { sku: "16SJ20", category: "BOWL", name: "16 OZ SQUAT CUP", pack: "20-25 / CS", packSize: "20-25 / CS", price: 59.73, active: true },
  { sku: "SM385815", category: "CANLINER", name: "60 GALLON BLACK CANLINER - 38X58 1.5 ML", pack: "10-10 / CS", packSize: "10-10 / CS", price: 36.94, active: true },
  { sku: "NL025-Q12", category: "CLEAN", name: "SUPER TOILET - 24% HCL BOWL CLEANER", pack: "12 QT / CS", packSize: "12 QT / CS", price: 53.23, active: true },
  { sku: "NL044-Q12", category: "CLEAN", name: "BACTIZYME - DRAIN CLEANER", pack: "12 QT / CS", packSize: "12 QT / CS", price: 77.41, active: true },
  { sku: "NL158-G4", category: "CLEAN", name: "BALANCE EC - FLOOR CLEANER", pack: "4 GL / CS", packSize: "4 GL / CS", price: 48.79, active: true },
  { sku: "NL206-G4", category: "CLEAN", name: "AT EZE - OVEN CLEANER", pack: "4 GL / CS", packSize: "4 GL / CS", price: 65.31, active: true },
  { sku: "NL220-G4", category: "CLEAN", name: "BLAZE 8 DEGREASER", pack: "4 GL / CS", packSize: "4 GL / CS", price: 60.51, active: true },
  { sku: "NL241-Q6W2", category: "CLEAN", name: "ARREST - ENZYME ELIMINATOR", pack: "6 QT / CS", packSize: "6 QT / CS", price: 46.37, active: true },
  { sku: "NL262-Q12", category: "CLEAN", name: "HI CLING - 9% HCL BOWL CLEANER", pack: "12 QT / CS", packSize: "12 QT / CS", price: 55.21, active: true },
  { sku: "NL269-G4", category: "CLEAN", name: "MARVALOSA - MULTIPURPOSE CLEANER", pack: "4 GL / CS", packSize: "4 GL / CS", price: 53.06, active: true },
  { sku: "NL303-G4", category: "CLEAN", name: "CONTEMPO - AUTO DISH WASH", pack: "4 GL / CS", packSize: "4 GL / CS", price: 57.26, active: true },
  { sku: "NL339-G4", category: "CLEAN", name: "RINSE AID - AUTO RINSE", pack: "4 GL / CS", packSize: "4 GL / CS", price: 86.67, active: true },
  { sku: "NL352-G4", category: "CLEAN", name: "LOW FOAM DELIMER", pack: "4 GL / CS", packSize: "4 GL / CS", price: 90.89, active: true },
  { sku: "NL356-G4", category: "CLEAN", name: "LO SUDS - GLASS WASH", pack: "4 GL / CS", packSize: "4 GL / CS", price: 56.66, active: true },
  { sku: "NL438-818", category: "CLEAN", name: "DEEP FAT - FRYER CLEANER", pack: "18 - 8OZ / CS", packSize: "18 - 8OZ / CS", price: 55.93, active: true },
  { sku: "NL535-G4", category: "CLEAN", name: "CITRA BLAZE DEGREASER", pack: "4 GL / CS", packSize: "4 GL / CS", price: 77.96, active: true },
  { sku: "NL611-G4", category: "CLEAN", name: "N601 SANITIZER - GALLONS", pack: "4 GL / CS", packSize: "4 GL / CS", price: 89.93, active: true },
  { sku: "NL611-P5", category: "CLEAN", name: "N601 SANITIZER - 5 GALLON PL", pack: "EA", packSize: "EA", price: 111.73, active: true },
  { sku: "NL627-G4", category: "CLEAN", name: "EVERPINE - PINE CLEANER", pack: "4 GL / CS", packSize: "4 GL / CS", price: 62.31, active: true },
  { sku: "NL763-Q12", category: "CLEAN", name: "SANI SPRITZ - DISINFECTANT CLEANER", pack: "12 QT / CS", packSize: "12 QT / CS", price: 51.97, active: true },
  { sku: "NL770-Q6W2", category: "CLEAN", name: "TABLE TIME - FOODSEVICE SANITIZER", pack: "6 QT / CS", packSize: "6 QT / CS", price: 27.43, active: true },
  { sku: "NL776-G4", category: "CLEAN", name: "Q64 DISINFECTANT CLEANER", pack: "4 GL / CS", packSize: "4 GL / CS", price: 79.70, active: true },
  { sku: "NL849-G4", category: "CLEAN", name: "CLEAN FREEZE - FREEZER CLEANER", pack: "4 GL / CS", packSize: "4 GL / CS", price: 148.27, active: true },
  { sku: "NL913-G4", category: "CLEAN", name: "CLEARLY THE BEST - GLASS CLEANER - GALLONS", pack: "4 GL / CS", packSize: "4 GL / CS", price: 35.84, active: true },
  { sku: "NL913-Q12", category: "CLEAN", name: "CLEARLY THE BEST - GLASS CLEANER - QUARTS", pack: "12 / CS", packSize: "12 / CS", price: 52.51, active: true },
  { sku: "NL933-P50", category: "CLEAN", name: "LAUNDRY DETERGENT - POWDERED - 50#", pack: "EA", packSize: "EA", price: 57.26, active: true },
  { sku: "NL939-P50", category: "CLEAN", name: "POWDERED PLEACH - 50#", pack: "EA", packSize: "EA", price: 66.03, active: true },
  { sku: "NL950-G4", category: "CLEAN", name: "GREEN KLEEN MULTI PURPOSE CLEANER", pack: "4 GL / CS", packSize: "4 GL / CS", price: 55.51, active: true },
  { sku: "CH12DEF", category: "CONTAINER", name: "12 OZ CLEAR HINGE TAKEOUT", pack: "2-100 / CS", packSize: "2-100 / CS", price: 33.13, active: true },
  { sku: "DC12", category: "CONTAINER", name: "12 OZ DESET CUP", pack: "800 / CS", packSize: "800 / CS", price: 69.90, active: true },
  { sku: "DC5", category: "CONTAINER", name: "5OZ DESERT CUP", pack: "1000 / CS", packSize: "1000 / CS", price: 62.54, active: true },
  { sku: "DC58", category: "CONTAINER", name: "DESERT CUP LIDS", pack: "500 / CS", packSize: "500 / CS", price: 52.89, active: true },
  { sku: "EFC-12", category: "CONTAINER", name: "12 OZ HOT FOOD COMBO", pack: "240 / CS", packSize: "240 / CS", price: 58.41, active: true },
  { sku: "EFC-16", category: "CONTAINER", name: "16 OZ HOT FOOD COMBO", pack: "240 / CS", packSize: "240 / CS", price: 61.09, active: true },
  { sku: "EFC-32", category: "CONTAINER", name: "32 OZ HOT FOOD COMBO", pack: "240 / CS", packSize: "240 / CS", price: 95.36, active: true },
  { sku: "EFC-8", category: "CONTAINER", name: "8 OZ HOT FOOD COMBO", pack: "240 / CS", packSize: "240 / CS", price: 55.50, active: true },
  { sku: "EHDC12C", category: "CONTAINER", name: "12 OZ CLEAR COMBO", pack: "240 / CS", packSize: "240 / CS", price: 42.56, active: true },
  { sku: "EHDC16C", category: "CONTAINER", name: "16 OZ CLEAR COMBO", pack: "240 / CS", packSize: "240 / CS", price: 41.83, active: true },
  { sku: "EHDC32C", category: "CONTAINER", name: "32 OZ CLEAR COMBO", pack: "240 / CS", packSize: "240 / CS", price: 71.34, active: true },
  { sku: "EHDC8C", category: "CONTAINER", name: "8 OZ CLEAR COMBO", pack: "240 / CS", packSize: "240 / CS", price: 39.44, active: true },
  { sku: "10J10", category: "CUP", name: "10 OZ FOAM DRINK CUP", pack: "40-25 / CS", packSize: "40-25 / CS", price: 61.39, active: true },
  { sku: "12J16", category: "CUP", name: "12 OZ FOAM DRINK CUP", pack: "40-25 / CS", packSize: "40-25 / CS", price: 78.00, active: true },
  { sku: "12PX", category: "CUP", name: "12 OZ POLY PLASTIC CUP", pack: "20-50 / CS", packSize: "20-50 / CS", price: 68.94, active: true },
  { sku: "12U16ESC", category: "CUP", name: "12 OZ ESCAPE CUP", pack: "50-20 / CS", packSize: "50-20 / CS", price: 235.76, active: true },
  { sku: "12X16G", category: "CUP", name: "12 OZ CAFE G CUP", pack: "40-25 / CS", packSize: "40-25 / CS", price: 92.84, active: true },
  { sku: "16EL", category: "CUP", name: "HOT DRINK SIP LIDS", pack: "10-100 / CS", packSize: "10-100 / CS", price: 72.41, active: true },
  { sku: "16PX", category: "CUP", name: "16 OZ POLY PLASTIC CUP", pack: "20-50 / CS", packSize: "20-50 / CS", price: 78.30, active: true },
  { sku: "20X16G", category: "CUP", name: "20 OZ CAFE G CUP", pack: "20-25 / CS", packSize: "20-25 / CS", price: 74.74, active: true },
  { sku: "8J8", category: "CUP", name: "8 OZ FOAM DRINK CUP", pack: "40-25 / CS", packSize: "40-25 / CS", price: 48.21, active: true },
  { sku: "TD24", category: "CUP", name: "24 OZ TRANSLUSCENT PLASTIC CUP", pack: "12-50 / CS", packSize: "12-50 / CS", price: 87.94, active: true },
  { sku: "Y10", category: "CUP", name: "10 OZ TRANSLUSCENT PLASTIC CUP", pack: "25-100 / CS", packSize: "25-100 / CS", price: 137.50, active: true },
  { sku: "Y12", category: "CUP", name: "12 OZ TRANSLUSCENT PLASTIC CUP", pack: "20-50 / CS", packSize: "20-50 / CS", price: 54.29, active: true },
  { sku: "Y16", category: "CUP", name: "16 OZ TRANSLUSCENT PLASTIC CUP", pack: "20-50 / CS", packSize: "20-50 / CS", price: 60.53, active: true },
  { sku: "Y35", category: "CUP", name: "3.5 OZ TRANSLUSCENT PLASTIC CUP", pack: "25-100 / CS", packSize: "25-100 / CS", price: 66.19, active: true },
  { sku: "Y5", category: "CUP", name: "5 OZ TRANSLUSCENT PLASTIC CUP", pack: "25-100 / CS", packSize: "25-100 / CS", price: 67.20, active: true },
  { sku: "Y7", category: "CUP", name: "7 OZ TRANSLUSCENT PLASTIC CUP", pack: "25-100 / CS", packSize: "25-100 / CS", price: 71.90, active: true },
  { sku: "Y9", category: "CUP", name: "9 OZ TRANSLUSCENT PLASTIC CUP", pack: "25-100 / CS", packSize: "25-100 / CS", price: 88.47, active: true },
  { sku: "R171002", category: "CUTLERY", name: "XHW WHITE SPOON", pack: "1000/CS", packSize: "1000/CS", price: 68.27, active: true },
  { sku: "R171003", category: "CUTLERY", name: "XHW WHITE KNIFE", pack: "1000/CS", packSize: "1000/CS", price: 68.27, active: true },
  { sku: "77907-15", category: "FILM", name: "15\" MEAT FILM", pack: "RL", packSize: "RL", price: 82.27, active: true },
  { sku: "77907-18", category: "FILM", name: "18\" MEAT FILM", pack: "RL", packSize: "RL", price: 98.74, active: true },
  { sku: "EFF122", category: "FILM", name: "12X2000 FILM", pack: "RL", packSize: "RL", price: 19.44, active: true },
  { sku: "EFF182", category: "FILM", name: "18X2000 FILM", pack: "RL", packSize: "RL", price: 28.01, active: true },
  { sku: "EFF242", category: "FILM", name: "24X2000 FILM", pack: "RL", packSize: "RL", price: 36.17, active: true },
  { sku: "E185-H", category: "FOIL", name: "18X500 HEAVY DUTY FOIL", pack: "RL", packSize: "RL", price: 33.74, active: true },
  { sku: "E185-S", category: "FOIL", name: "18X500 STANDARD FOIL", pack: "RL", packSize: "RL", price: 24.96, active: true },
  { sku: "EFT100", category: "FOOD TRAY", name: "1# FOOD TRAY", pack: "4-250 / CS", packSize: "4-250 / CS", price: 40.39, active: true },
  { sku: "EFT1000", category: "FOOD TRAY", name: "10# FOOD TRAY", pack: "2-125 / CS", packSize: "2-125 / CS", price: 66.09, active: true },
  { sku: "EFT200", category: "FOOD TRAY", name: "2# FOOD TRAY", pack: "4-250 / CS", packSize: "4-250 / CS", price: 47.73, active: true },
  { sku: "EFT300", category: "FOOD TRAY", name: "3# FOOD TRAY", pack: "2-250 / CS", packSize: "2-250 / CS", price: 34.00, active: true },
  { sku: "EFT50", category: "FOOD TRAY", name: "1/2# FOOD TRAY", pack: "4-250 / CS", packSize: "4-250 / CS", price: 33.89, active: true },
  { sku: "EFT500", category: "FOOD TRAY", name: "5# FOOD TRAY", pack: "2-250 / CS", packSize: "2-250 / CS", price: 43.99, active: true },
  { sku: "B18B", category: "FREEZER", name: "18\" BUTCHER PAPER", pack: "RL", packSize: "RL", price: 39.64, active: true },
  { sku: "NG18", category: "FREEZER", name: "18\"X1100' 45# FREEZER PAPER", pack: "RL", packSize: "RL", price: 64.91, active: true },
  { sku: "NG24", category: "FREEZER", name: "24\"X1100' 45# FREEZER PAPER", pack: "RL", packSize: "RL", price: 86.54, active: true },
  { sku: "ELEPFL2003", category: "GLOVE", name: "LG PF LATEX GLOVE", pack: "10-100 / CS", packSize: "10-100 / CS", price: 77.19, active: true },
  { sku: "ELEPFM2002", category: "GLOVE", name: "MED PF LATEX GLOVE", pack: "10-100 / CS", packSize: "10-100 / CS", price: 77.19, active: true },
  { sku: "ELEPFXL2004", category: "GLOVE", name: "XL PF LATEX GLOVE", pack: "10-100 / CS", packSize: "10-100 / CS", price: 77.19, active: true },
  { sku: "ENEL2003", category: "GLOVE", name: "LG PF NITRILE GLOVE", pack: "10-100 / CS", packSize: "10-100 / CS", price: 70.87, active: true },
  { sku: "ENEM2002", category: "GLOVE", name: "MED PF NITRILE GLOVE", pack: "10-100 / CS", packSize: "10-100 / CS", price: 70.87, active: true },
  { sku: "ENEXL2004", category: "GLOVE", name: "XL PF NITRILE GLOVE", pack: "10-100 / CS", packSize: "10-100 / CS", price: 70.87, active: true },
  { sku: "EVPXL3004", category: "GLOVE", name: "XL POWDERED VINYL GLOVE", pack: "10-100 / CS", packSize: "10-100 / CS", price: 28.04, active: true },
  { sku: "GL-L", category: "GLOVE", name: "LG POLY GLOVE", pack: "10-100 / CS", packSize: "10-100 / CS", price: 12.73, active: true },
  { sku: "GL-M", category: "GLOVE", name: "MED POLY GLOVE", pack: "10-100 / CS", packSize: "10-100 / CS", price: 11.66, active: true },
  { sku: "1014", category: "MEAT TRAY", name: "9.75 X 14 X 1 BLACK TRAY", pack: "100/CS", packSize: "100/CS", price: 40.97, active: true },
  { sku: "10S", category: "MEAT TRAY", name: "5.88 X 10.75 X .63 BLACK TRAY", pack: "500 / CS", packSize: "500 / CS", price: 50.17, active: true },
  { sku: "17S", category: "MEAT TRAY", name: "4.5 X 8.5 X .63 BLACK TRAY", pack: "1000 / CS", packSize: "1000 / CS", price: 69.84, active: true },
  { sku: "1S", category: "MEAT TRAY", name: "5.25 X 5.25 X 5 BLACK TRAY", pack: "1000 / CS", packSize: "1000 / CS", price: 59.91, active: true },
  { sku: "2", category: "MEAT TRAY", name: "5.75 X 8.25 X 1 BLACK TRAY", pack: "500 / CS", packSize: "500 / CS", price: 37.66, active: true },
  { sku: "20S", category: "MEAT TRAY", name: "6.31 X 8.63 X .63 BLACK TRAY", pack: "500 / CS", packSize: "500 / CS", price: 48.33, active: true },
  { sku: "2S", category: "MEAT TRAY", name: "5.75 X 8.25 X .63 BLACK TRAY", pack: "500 / CS", packSize: "500 / CS", price: 37.20, active: true },
  { sku: "4P", category: "MEAT TRAY", name: "6.75 X 9.25 X 1.31 BLACK TRAY", pack: "500 / CS", packSize: "500 / CS", price: 58.23, active: true },
  { sku: "4S", category: "MEAT TRAY", name: "7.25 X 9.25 X .63 BLACK TRAY", pack: "500 / CS", packSize: "500 / CS", price: 55.73, active: true },
  { sku: "BEVNAP", category: "PAPER", name: "BEVERAGE NAPKIN", pack: "", packSize: "", price: 21.08, active: true },
  { sku: "ELCP660013", category: "PAPER", name: "CENTERPULL TOWEL", pack: "6-600 / CS", packSize: "6-600 / CS", price: 32.16, active: true },
  { sku: "F710", category: "PAPER", name: "CUBE BOX KLEENEX", pack: "36 - 90 / CS", packSize: "36 - 90 / CS", price: 86.61, active: true },
  { sku: "NOVA 3000", category: "PAPER", name: "DINNER NAPKIN", pack: "20-135 / CS", packSize: "20-135 / CS", price: 39.03, active: true },
  { sku: "NOVA2", category: "PAPER", name: "FACIAL TISSUE", pack: "30-100 / CS", packSize: "30-100 / CS", price: 22.14, active: true },
  { sku: "NOVA500", category: "PAPER", name: "2 PLY STANDARD TOILET TISSUE", pack: "96/RL / CS", packSize: "96/RL / CS", price: 58.91, active: true },
  { sku: "T411", category: "PAPER", name: "SERVE ONE DISPENSER NAPKIN", pack: "16-376 / CS", packSize: "16-376 / CS", price: 116.66, active: true },
  { sku: "YTHBO500", category: "PLATE", name: "SCHOOL TRAY", pack: "500 / CS", packSize: "500 / CS", price: 43.87, active: true },
  { sku: "100PC", category: "SOUFFLE", name: "1 OZ CLEAR SOUFFLE CUP", pack: "20-125 / CS", packSize: "20-125 / CS", price: 34.63, active: true },
  { sku: "200PC", category: "SOUFFLE", name: "2 OZ CLEAR SOUFFLE CUP", pack: "20-125 / CS", packSize: "20-125 / CS", price: 36.37, active: true },
  { sku: "325PC", category: "SOUFFLE", name: "3.25 OZ CLEAR SOUFFLE CUP", pack: "20-125 / CS", packSize: "20-125 / CS", price: 55.71, active: true },
  { sku: "400PC", category: "SOUFFLE", name: "4 OZ CLEAR SOUFFLE CUP", pack: "20-125 / CS", packSize: "20-125 / CS", price: 59.61, active: true },
  { sku: "550PC", category: "SOUFFLE", name: "5.5 OZ SOUFFLE CUPS", pack: "20-125 / CS", packSize: "20-125 / CS", price: 86.66, active: true },
  { sku: "PL100N", category: "SOUFFLE", name: "1 OZ PLASTIC LID", pack: "20-125 / CS", packSize: "20-125 / CS", price: 26.23, active: true },
  { sku: "PL200N", category: "SOUFFLE", name: "2 OZ PLASTIC LID", pack: "20-125 / CS", packSize: "20-125 / CS", price: 34.81, active: true },
  { sku: "PL4N", category: "SOUFFLE", name: "PLASTIC LID FOR 3.25 - 4 - 5.5 OZ SOUFFLE CUPS", pack: "20-125 / CS", packSize: "20-125 / CS", price: 43.30, active: true },
  { sku: "BWKJSTU775T50", category: "STRAWS", name: "JUMBO UNWRAPPED STRAW", pack: "50-250 / CS", packSize: "50-250 / CS", price: 61.63, active: true },
  { sku: "BWKJSTW775CLR", category: "STRAWS", name: "JUMBO WRAPPED STRAW", pack: "12000 / CS", packSize: "12000 / CS", price: 76.06, active: true },
  { sku: "ECK525BK", category: "STRAWS", name: "BLACK SIP STIX", pack: "10-1000 / CS", packSize: "10-1000 / CS", price: 22.20, active: true },
  { sku: "ECK525NE", category: "STRAWS", name: "NEON SIP STIX", pack: "10-1000 / CS", packSize: "10-1000 / CS", price: 22.20, active: true },
  { sku: "ECK775BK", category: "STRAWS", name: "BLACK COLLINS STRAW", pack: "10-500 / CS", packSize: "10-500 / CS", price: 26.00, active: true },
  { sku: "ECK775NE", category: "STRAWS", name: "NEON COLLINS STRAW", pack: "10-500 / CS", packSize: "10-500 / CS", price: 26.00, active: true },
];