// Auto-generated clean data.js from products.csv (strict CSV categories)
window.customers = [
  { id: "CUST-0001", name: "3rd Base", city: "Carlton", state: "MN" },
  { id: "CUST-0002", name: "Alpine Bar", city: "Duluth", state: "MN" },
  { id: "CUST-0003", name: "B&B Market", city: "Cloquet", state: "MN" },
  { id: "CUST-0007", name: "Barnum Liquor", city: "Barnum", state: "MN" },
  { id: "CUST-0004", name: "Bergeys", city: "Duluth", state: "MN" },
  { id: "CUST-0005", name: "Bird's Bar", city: "Superior", state: "WI" },
  { id: "CUST-0006", name: "Blue Max", city: "Duluth", state: "MN" },
  { id: "CUST-0008", name: "Blueberry Bowl", city: "Deer River", state: "MN" },
  { id: "CUST-0009", name: "Bricks", city: "Wrenshall", state: "MN" },
  { id: "CUST-0012", name: "Carlton Meat", city: "Carlton", state: "MN" },
  { id: "CUST-0070", name: "Carlton VFW", city: "Carlton", state: "MN" },
  { id: "CUST-0071", name: "Caywood Country Store", city: "Saginaw", state: "MN" },
  { id: "CUST-0010", name: "Chalstroms", city: "Duluth", state: "MN" },
  { id: "CUST-0072", name: "Chisholm Korner Store", city: "Chisholm", state: "MN" },
  { id: "CUST-0013", name: "Chisholm Vaughn", city: "Chisholm", state: "MN" },
  { id: "CUST-0014", name: "Cook Muni Bar", city: "Cook", state: "MN" },
  { id: "CUST-0016", name: "Country Corner", city: "Brookston Legion", state: "MN" },
  { id: "CUST-0017", name: "Cromwell Liquor", city: "Cromwell", state: "MN" },
  { id: "CUST-0018", name: "Duluth Korner Store 000", city: "Duluth", state: "MN" },
  { id: "CUST-0019", name: "Duluth Korner Store 700", city: "Duluth", state: "MN" },
  { id: "CUST-0020", name: "El Dorado", city: "Oliver", state: "WI" },
  { id: "CUST-0021", name: "Four Seasons Meat", city: "Coleraine", state: "MN" },
  { id: "CUST-0022", name: "Grand Rapids Eagles", city: "Grand Rapids", state: "MN" },
  { id: "CUST-0023", name: "Hermantown Korner Store", city: "Hermantown", state: "MN" },
  { id: "CUST-0024", name: "Hi Banks", city: "Duluth", state: "MN" },
  { id: "CUST-0025", name: "Hotel Rapids", city: "Grand Rapids", state: "MN" },
  { id: "CUST-0073", name: "IM Hotel", city: "Grand Rapids", state: "MN" },
  { id: "CUST-0027", name: "Izzys", city: "Superior", state: "WI" },
  { id: "CUST-0030", name: "Knuckleheads", city: "Hill City", state: "MN" },
  { id: "CUST-0029", name: "Kom On Inn", city: "Duluth", state: "MN" },
  { id: "CUST-0031", name: "Lake Walk Pharmacy", city: "Duluth", state: "MN" },
  { id: "CUST-0032", name: "Larry's Service", city: "Floodwood", state: "MN" },
  { id: "CUST-0033", name: "Last Chance Liquor", city: "Cook", state: "MN" },
  { id: "CUST-0034", name: "Locker Room", city: "Coleraine", state: "MN" },
  { id: "CUST-0074", name: "Mahtowa Tavern", city: "Mahtowa", state: "MN" },
  { id: "CUST-0075", name: "Mr D's", city: "Duluth", state: "MN" },
  { id: "CUST-0076", name: "Norman's", city: "Orr", state: "MN" },
  { id: "CUST-0038", name: "Northland Pharmacy", city: "Duluth", state: "MN" },
  { id: "CUST-0040", name: "Northwoods Meat", city: "Remer", state: "MN" },
  { id: "CUST-0041", name: "Orr Muni", city: "Orr", state: "MN" },
  { id: "CUST-0042", name: "Pelican Bay Foods", city: "Orr", state: "MN" },
  { id: "CUST-0043", name: "Powerhouse", city: "Proctor", state: "MN" },
  { id: "CUST-0044", name: "Proctor Keyboard", city: "Proctor", state: "MN" },
  { id: "CUST-0045", name: "Proctor Moose", city: "Proctor", state: "MN" },
  { id: "CUST-0077", name: "Remer", city: "Remer", state: "MN" },
  { id: "CUST-0078", name: "Remer Liquor Store", city: "Remer", state: "MN" },
  { id: "CUST-0052", name: "River Inn", city: "Cloquet", state: "MN" },
  { id: "CUST-0046", name: "Roscoes", city: "Duluth", state: "MN" },
  { id: "CUST-0047", name: "Round Up", city: "Duluth", state: "MN" },
  { id: "CUST-0048", name: "RT Quinlans", city: "Duluth", state: "MN" },
  { id: "CUST-0049", name: "Rustic Bar", city: "Duluth", state: "MN" },
  { id: "CUST-0053", name: "S&S Meats", city: "Grand Rapids", state: "MN" },
  { id: "CUST-0054", name: "Snyders", city: "Duluth", state: "MN" },
  { id: "CUST-0055", name: "Strikers", city: "Superior", state: "WI" },
  { id: "CUST-0056", name: "Superior Eagles", city: "Superior", state: "WI" },
  { id: "CUST-0057", name: "Superior Korner Store", city: "Superior", state: "WI" },
  { id: "CUST-0058", name: "T Patton's", city: "Orr", state: "MN" },
  { id: "CUST-0059", name: "Tappa Keg", city: "Duluth", state: "MN" },
  { id: "CUST-0066", name: "The Jack", city: "Cloquet", state: "MN" },
  { id: "CUST-0060", name: "The Landing", city: "Two Harbors", state: "MN" },
  { id: "CUST-0061", name: "The Shack", city: "Superior", state: "WI" },
  { id: "CUST-0062", name: "TJ's", city: "Mahtowa", state: "MN" },
  { id: "CUST-0067", name: "Tom & Jerry's", city: "Chisholm", state: "MN" },
  { id: "CUST-0063", name: "Tower Ave Tavern", city: "Superior", state: "WI" },
  { id: "CUST-0064", name: "Two Harbors Legion", city: "Two Harbors", state: "MN" },
  { id: "CUST-0065", name: "Two Harbors Moose", city: "Two Harbors", state: "MN" },
  { id: "CUST-0068", name: "Valentini's", city: "Chisholm", state: "MN" },
  { id: "CUST-0069", name: "Wizards", city: "Nashauwauk", state: "MN" },
];

window.products = [
];
